# The Docker image that will be used to build your app
image: docker-registry.univ-nantes.fr/bousse-e/docker-antora-assembler
# Functions that should be executed before the build script is run
before_script:
  #- bundle install
pages:
  script:
    - antora --stacktrace generate antora-playbook.yml     
    - mkdir -p public
    - rsync -r build/site/ public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
