stages:
  - pre-build
  - after-pre-build
  - build1
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

antora:
  image: docker-registry.univ-nantes.fr/bousse-e/docker-antora-assembler:12
  services:
    - name: docker.io/yuzutech/kroki
      alias: kroki
  stage: build1
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - build/antora-cache
  script:
    - antora --stacktrace generate antora-playbook.yml
  artifacts:
    paths:
      - build

check-links:
  stage: test
  image:
    name: ghcr.io/linkchecker/linkchecker:latest
    entrypoint: [""]
  script:
    - cd build/site
    - linkchecker --ignore-url 'https://fonts.googleapis.com/.*'
      --ignore-url 'https://cdnjs.cloudflare.com/.*'
      --ignore-url '.*reveal.js.*'
      --ignore-url '.*isi.pdf'
      index.html

pages:
  stage: publish
  script:
    - rm -rf public
    - mv build/site public
  artifacts:
    paths:
      - public
