site:
  title: Projet Trivial Pursuit - Développement
  url: https://naomod.univ-nantes.io/sd/slides/
  start_page: trivial-doc::index.adoc
asciidoc:
  attributes:
    author: Gerson Sunyé
    email: gerson.sunye@univ-nantes.fr
    #plantuml-server-url: http://www.plantuml.com/plantuml
    plantuml-config: https://gitlab.univ-nantes.fr/naomod/defaults/-/blob/main/plantuml/puml-theme-sober.puml
    listing-caption: Listing@
    kroki-fetch-diagram: true
    kroki-server-url: http://kroki:8000
    sectnums: true
  extensions:
    - asciidoctor-kroki
content:
  sources:
  - url: https://gitlab.univ-nantes.fr/naomod/sd/trivial-pursuit.git
    branches:  main
    start_path: trivial-doc
ui:
  bundle:
    url: https://gitlab.univ-nantes.fr/sunye-g/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: "./antora-custom-theme/supplemental-ui"