@startuml
!include https://gitlab.univ-nantes.fr/naomod/defaults/-/raw/main/plantuml/puml-theme-sober.puml
start
fork
:Delete old cache files;
:Create new cache folder;
fork again
:Delete log file;
end fork
end
@enduml