@startuml
package "My System" {
interface "Connect" as connect
interface "Join" as Cli1
interface "Play" as pl
interface "Initialise" as init

interface "AddData" as addData
interface "GetData" as getData
interface "UpdateData" as updateData

component "Game Data " as LobbyServer
component "Game server" as MiddlewareClient1


[LobbyServer] -up-() addData
MiddlewareClient1 --( addData

[LobbyServer] -up-() getData
MiddlewareClient1 --( getData

[LobbyServer] -up-() updateData
MiddlewareClient1 --( updateData




[Client Game] --( Cli1
Cli1 -- [MiddlewareClient1]

[Client Game] --( connect
[MiddlewareClient1] -up-() connect

[Client Game] --( pl
pl -- [MiddlewareClient1]

[Client Game] --( init
init -- [MiddlewareClient1]

}
@enduml