@startuml
package "My System" {
interface "Interface A" as Web1
interface "Interface B" as Cli1
interface "Account" as Web2
interface "Interface D" as Lobby

component "Component A" as GameServer
component "Component L" as LobbyServer
component "Component C" as MiddlewareClient1
component "Game server" as MiddlewareClient2

[Client web 1]
[Client web 2]
}


[LobbyServer] -up-() Lobby

[GameServer] --( Lobby
MiddlewareClient1 --( Lobby
MiddlewareClient2 --( Lobby

[Client web 1] --() Cli1
Cli1 )-- [MiddlewareClient1]

[Client web 2] --( Web2
[MiddlewareClient2] -up-() Web2

[Client web 1] --( Web1
[MiddlewareClient1] -up-() Web1
@enduml