@startuml
!include https://gitlab.univ-nantes.fr/naomod/defaults/-/raw/main/plantuml/puml-theme-sober.puml

node Navigateur {
    artifact WebClient as "Client Web"
}
node Server {
    artifact GameServer as "Serveur TP"
}

node Database {
    artifact DBMS as "SGBD"
}

WebClient -right- Server : \t TCP/IP - WebSockets
GameServer -up- DBMS : JDBC

@enduml