:project: Trivial Pursuit
:source-highlighter: rouge
:rouge-css: style
:icons: font

= Analyse du domaine

== Introduction

L'objectif de ce chapitre est de présenter le résultat de l'analyse du domaine du jeu *{project}*, sous la forme d'un _modèle du domaine_.

Le modèle du domaine est un système d'abstractions qui décrit des aspects sélectionnés d'un domaine{nbsp}:
une sphère de connaissances, d'influences ou d'activités. 

Ce modèle sera utilisé pour résoudre des problèmes liés à ce domaine. 
Le modèle de domaine est donc une représentation des concepts significatifs du monde réel,
qui sont pertinents pour la solution logicielle. 
Les concepts comprennent les données et les règles qui s'appliquent à ces données. 
Le modèle de domaine exploite le langage naturel du domaine.

Le modèle de domaine utilise généralement le vocabulaire du domaine, ce qui permet de communiquer une représentation du modèle aux parties prenantes non techniques. 
Il ne doit pas faire référence à des implémentations techniques telles que des bases de données ou des composants logiciels en cours de conception.

== Analyse préliminaire

*{project}* est un jeu de plateau, dans lequel le progrès est déterminé par la capacité d'un joueur à répondre aux questions de culture générale. 

Le jeu est composé d'un plateau de jeu, de 400 cartes de questions, de 6 pions xref:termes.adoc#Camembert[camembert], de 36 xref:termes.adoc#Triangle[triangles] de couleurs différentes et d'un dé.

Les questions sont réparties en 6 catégories différentes, 
synthétisées dans le tableau ci-dessous{nbsp}: 

.Catégories des questions
|===
| Couleur | Catégorie 

| Bleu 
| Géographie

|Rose
| Divertissements

| Jaune
| Histoire

| Violet
| Arts et Littérature

| Vert
| Sciences et Nature

| Orange
| Sports et Loisirs

|===

=== Plateau et Cases

Un plateau est composé d'une case début et de 72 cases de couleurs différentes.
Il se présente sous la forme d'une roue avec 1 cercle extérieur et 6 rayons.

Au centre,  à l'intersection des rayions, se trouve la case Départ.
Aux 6 intersections des rayons avec le cercle se trouvent 6 cases "Quartiers Généraux de Catégorie", sur lesquelles est dessiné à chaque fois un gros triangle de couleur différente.


.Plateau et Cases
[plantuml, cd-plateau-cases]
....
include::example$cd-plateau-cases.plantuml[]
....

.Invariants
[source,ocl]
----
context Case
-- Tous les voisins d'une case l'ont aussi comme voisin.
inv: self.voisins->forAll(each | each.voisins->contains(self))
----

=== Cartes, Questions et Réponses

.Cartes, Questions et Réponses
[plantuml, cd-cartes-questions-reponses]
....
include::example$cd-cartes-questions-reponses.plantuml[]
....

// TODO


== Modèle du domaine

[NOTE]
====
Décrivez ici les classes conceptuelles du domaine, ainsi que leurs attributs et associations.
====

.Classes conceptuelles
[plantuml]
....
include::example$cd-domain-model.plantuml[]
....

== Cas d'utilisation

=== UC-{counter:uc} -- Préparation

include::partial$uc-preparation.adoc[]

=== UC-{counter:uc} -- Tour de jeu

include::partial$uc-tour.adoc[]


=== Attaquer

include::partial$uc-attaque.adoc[]


== Activités

=== Choix d'une couleur

=== Election du _Général_

=== Distribution des missions

=== Distribution des armées

.Tableau 
[cols="40h,20,20,20"]
|===
| Nombre de joueurs
| 2
| 3
| 4
| 5
| 6

| Nombre d'armées à placer
| x
| x
| x
| x
| x

|===

=== Distribution des cartes Risk

=== Placement des armées

=== Renforcement des territoires

=== Constitution de la pile de cartes


=== Créer la planète Artemina

1) Placer 1 exemplaire des 10 cartes Lieu devant la créature
en 2 rangées de chacune 5 cartes, par ordre croissant,
2) Placer le pion Balise à côté de la carte Plage.

post-condition:: .

.Mon diagramme de classes
[plantuml, od-creer-planete-artemia-apres, svg]
....
hide circle
skinparam monochrome true

object A
....

=== Créer la pioche Traque

Mélanger et placer face cachée les cartes Traque à proximité de la Créature.

=== Créer la pioche Survie

Mélanger et placer face cachée les cartes Survie à proximité des Traqués.

=== Préparer la main de la Créature

. La créature place le plateau au centre de la table sur la face de son choix,
. La créature place le pion Secours et le pion Assimilation sur le chiffre de leur piste respective correspondant au nombre de joueurs,
. La créature pioche 3 cartes Traque et prend les 3 jetons Traque (Créature, Cible et Artemia).

=== Préparer la main des Traqués

. Chaque traqué prend 3 pions Volonté, les pions Volonté restants sont retirés du jeu,
. Chaque traqué prend un set de 5 cartes Lieu numérotées de 1 à 5, les cartes inutilisées sont retirées du jeu,
. Chaque traqué pioche 1 carte Survie.

=== Former la réserve

Former la réserve Lieux avec les cartes Lieu numérotées de 6 à 10.
Placer près du plateau le nombre d’exemplaires de chaque carte Lieu
correspondant au nombre de Traqués (voir le tableau "Traqués"),
face visible, les cartes inutilisées sont retirées du jeu.

.Tableau Traqués/Cartes lieu
[cols="40h,20,20,20"]
|===
| Nombre de Traqués
| 1
| 2-3
| 4-6

| Nombre de cartes lieu (6-10)
| 1
| 2
| 3

|===

=== Résister

Lorsqu'un Traqué Résiste, il choisit 1 des cas suivants :
- perdre 1 pion Volonté pour choisir et reprendre en main 2 cartes Lieu de sa défausse,
- perdre 2 pions Volonté pour choisir et reprendre en main 4 cartes Lieu de sa défausse.
Si par cette action un Traqué perd son dernier pion Volonté, il doit résoudre Lâcher prise.

=== Résister (avec plus 1 pion volonté)

.Trinity avant de résister
[plantuml, trinity-resiste-avant, png]
....
skinparam monochrome true
object  trinity  {
    name = "Trinity"
}

object Antre
object Plage

trinity -- "main" Antre
trinity -- "main" Plage
....

.Trinity après avoir résisté
[plantuml, trinity-resiste-apres, png]
....
skinparam monochrome true
object  trinity  {
    name = "Trinity"
}
....

pre-conditon:: le joueur a plus d'un pion de volonté
post-condition:: Le joueur perd 1 pion volonté ET
le joueur récupère jusqu'à 2 cartes de la défausse

=== Résister (avec 1 pion volonté)

pre-condition:: le joueur n'a qu'un seul pion de volonté
post-condition::
le joueur lache prise

=== Lâcher prise

.Trinity avant de lâcher prise
[plantuml, trinity-lache-prise, png]
....
skinparam monochrome true

object Partie {
    positionCreature = 2
}
object  trinity  {
    name = "Trinity"
    pionVolonté = 1
}

object Antre
object Plage
object "L'abris" as Abris
object Rover
object Rivière
object Jungle

trinity -- "main" Antre
trinity -- "main" Plage
trinity -- "défausse" Rover
trinity -- "défausse" Abris
trinity -- "défausse" Rivière
trinity -- "défausse" Jungle
....

.Trinity après avoir lâché prise
[plantuml, trinity-a-lache-prise, png]
....
skinparam monochrome true
object partie {
}

object plateau {
    positionPionSecours = 1
    positionPionAssimilation = 3
}

object  trinity  {
    name = "Trinity"
    pionVolonté = 3
}

object Antre
object Plage
object "L'abris" as Abris
object Rover
object Rivière
object Jungle

trinity -- "main" Antre
trinity -- "main" Plage
trinity -- "main" Rover
trinity -- "main" Abris
trinity -- "main" Rivière
trinity -- "main" Jungle

partie -> plateau
partie -> "traqué" trinity : \t\t
....
pre-condition:: Le joueur n'a plus de jeton (?)

post-conditions:: Le pion Assimlilation avance d'une position ET
toutes les cartes de la défausse passent à la main ET
le joueur récupère 3 points de volonté

=== Avancer le pion Secours

=== Avancer le pion Assimilation

.Exemple d'avancement d'un pion secours (avant)
[plantuml, od-avancer-pion-secours-avant, svg]
....
hide circle
skinparam monochrome true

object "Pion Secours" as secours
object ":Case Traque" as traque7 {
    position = 7
}
object ":Case Traque" as traque6 {
    position = 6
}
secours -[hidden] traque6 : \t\t\t
secours --> traque7
....

.Exemple d'avancement d'un pion secours (après)
[plantuml, od-avancer-pion-secours-apres, svg]
....
hide circle
skinparam monochrome true

object "Pion Secours" as secours
object ":Case Traque" as traque7 {
    position = 7
}
object ":Case Traque" as traque6 {
    position = 6
}
secours -[#blue]> traque6 : \t\t\t
secours -[hidden]-> traque7
....

.Exemple d'avancement d'un pion assimilation (avant)
[plantuml, od-avancer-pion-assimilation-avant, svg]
....
hide circle
skinparam monochrome true

object "Pion Assimilation" as secours
object ":Case Créature" as creature7 {
    position = 7
}
object ":Case Créature" as creature6 {
    position = 6
}
secours -[hidden] creature6 : \t\t\t
secours --> creature7
....

.Exemple d'avancement d'un pion assimilation (après)
[plantuml, od-avancer-pion-assimilation-apres, svg]
....
hide circle
skinparam monochrome true

object "Pion Assimilation" as assimilation
object ":Case Créature" as creature7 {
    position = 7
}
object ":Case Créature" as creature6 {
    position = 6
}
assimilation -[#red]> creature6 : \t\t\t
assimilation -[hidden]-> creature7
....






.Jetons
[plantuml, cd-jetons, svg]
....
hide circle
skinparam monochrome true

class Jeton
Jeton <|-- Créature
Jeton <|-- Cible
Jeton <|-- Artemia
....

.Pions
[plantuml, cd-pions, svg]
....
hide circle
skinparam monochrome true

Pion <|-- Balise
Pion <|-- Secours
Pion <|-- Assimilation
Pion <|-- Volonté
....

.Plateau
[plantuml, cd-plateau, svg]
....
hide circle
skinparam monochrome true

class Plateau
class Case
class "Case Créature" as creature
class "Case Traqué" as traque

Case <|-- creature
Case <|-- traque

traque   "piste [18]" --* Plateau
creature  "piste [12]" --* Plateau
....


.Cartes Lieu
[plantuml, cd-cartes-lieu, svg]
....
hide circle
skinparam monochrome true
class Lieu {
    effet()
}

class Antre {

}

Lieu <|-- Antre
Lieu <|-- Jungle
Lieu <|-- Rivière
Lieu <|-- Plage
Lieu <|-- Rover
Lieu <|-- Marais
Lieu <|-- Abris
Lieu <|-- Epave
Lieu <|-- Source
Lieu <|-- Artefact
....

=== Opérations

.Antre::effet()
[source,ocl]
----
CarteAntre::effet()
pre:
la carte est sur la table ET
il n'y a pas de jeton créature sur la carte antre du plateau

post:
le joueur reprend en main les cartes de la défausse OU
le joueur copie le pouvoir de la carte avec le jeton créature
----

- Jungle::effet()
- Rivière::effet()
- Plage::effet()
- Rover::effet()
- Marais::effet()
- Abris::effet()


