== Use Case Initialisation

Use Case Template. Copyright (c) 2004-2005 TechnoSolutions Corporation

*Use Case:* Initialisation

*Id*: UC- 2

*Description* Initialisation et mise en place d'une partie de RISK

*Level:* User Goal

*Primary Actor* Jeu

*Supporting Actors* Joueurs

*Stakeholders and Interests* Pioche Défausse Carte Territoire Continent

*Pre-Conditions*

Au moins 3 joueurs sont présents.

*Post Conditions*

[.underline]#Success end condition#

Le jeu a été correctement mis en place selon les règles de RISK. Chaque territoire est en possession d'un joueur. Chaque territoire supporte une ou plusieurs armées du joueur possédant ce territoire. La pioche est remplie avec toutes les cartes du jeu dans un ordre aléatoire.

[.underline]#Failure end condition#:

Un des joueurs ne place pas une de ses armées lorsque c'est à son tour de le faire. Il bloque l'initialisation.

[.underline]#Minimal Guarantee#

La partie ne peut pas continuer tant que le jeu n'a pas été correctement initialisé.

*Trigger*

Les joueurs sont prêts à jouer.

=== Main Success Scenario

[arabic]
. On distribue à chaque joueur des unités d'armé selon le nombre de joueurs total. 35 unités pour 3 joueurs, 30 pour 4, 25 pour 5 et 20 pour 6.
. L'ordre de jeu des joueurs à l'initialisation et lors des tours qui suivront est déterminé aléatoirement avec un lancé de dé 6. Chaque joueur lance le dé et le joueur ayant le plus grand chiffre commence. Les joueurs jouent ensuite dans le sens des aiguille d'une montre après le premier joueur *Extension 1*.
. Les joueurs posent tour à tour une de leur unité d'armé sur les territoires non occupés par un autre joueur, avec obligation de placer sur un territorie innocupé si possible. *Extension 2*.
. Répéter 3. tant qu'il reste des armées aux joueurs.
. On mélange toutes les cartes du jeu et les met dans la pioche.

=== Extensions

{empty}1. Si il y a une égalité entre les premiers, ces joueurs rejouent jusqu'à ce qu'il y ai un gagnant.

{empty}2. Si le territoire était innocupé par une armée, le joueur qui y pose l'armée se l'approprie.

*Frequency:* Une seule fois

