== Cas d'utilisation

=== #1 : Mise en place du jeu

*pré-condition*

* Communication établie entre l'arbitre et chaque joueur.
* Un mode de jeu à été déterminé.

*postcondition*

* Les joueurs ont le même nombre d'armées.
* Les joueurs ont un écart maximal de 1 entre leurs nombres de territoires
* Aucune mission n'est accomplie.

*Scénario*

. #1.1 <<AttributionMissions>>
. L'arbitre distribue le même nombre d'armées à chaque joueurs selon le nombre total de joueurs : 2 joueurs->40 armées, 3 joueurs->35 armées, 4->30, 5->25, 6-> 20
. S'il y a 2 joueurs : <<MiseADeuxJoueurs>>, puis ignorer les étapes suivantes
. L'arbitre attribue une couleur différente à chaque joueur.
. L'arbitre lance 1d6/joueur.
Le joueur dont le lancé est le plus élevé est l'initiateur.
. Si le mode jeu est "secret mission risk" alors l'arbitre ditribue aléatoirement les territoires aux joueurs.
On ignore les 3 étapes d'attribution des territoires qui suivent.
. L'initiateur place une de ses armées sur un territoire non occupé qu'il proclame (le territoire lui est attribué).
. L'arbitre désigne le joueur à gauche du précédent qui doit faire de même.
. On recommence l'étape précédente jusqu'à-ce que tous les 42 territoires soient occupés.
. L'initiateur place une armée sur un de ses territoires.
. Le joueur désigné comme suivant fait de même
. On recommence l'étape précédente jusqu'à-ce que toutes les armées des joueurs soient placées.
. L'arbitre mélange les cartes territoires et joker ensemble et en forme une pile cachée.
. L'initiateur joue le 1er tour de jeu.

[#AttributionMissions]
==== #1.1 Attribution des missions

. Selon le mode de jeu, l'arbitre attribue à chaque joueur une mission :
.. Partie à 2 joueurs : défaire l'adversaire, le 3e joueur neutre ne compte pas.
.. world domination risk : tout les joueurs on pour mission de posséder tout les territoires du monde.
.. capital risk : capturer toutes les capitales
.. (4 joueurs) 2 capital risk : capturer 2 capitales en plus de la sienne.
.. (5 ou 6 joueurs) 3 capital risk : capturer 3 capitales en plus de la sienne.
.. (3 à 6 joueurs) secret mission risk : être le premier à accomplir la mission secrète indiquée sur la carte donnée au hasard par l'arbitre.

[#MiseADeuxJoueurs]
==== #1.2 Mise en place à deux joueurs

. L'arbitre crée un troisième joueur (le joueur neutre)
. L'arbitre attribue une couleur différente à chaque joueur.
. L'arbitre répartit aux hasard les territoires entre les 3 joueurs (14 territoires par joueur).
. L'arbitre place une armée sur chaque territoire.
. L'arbitre choisit au hasard qui des 2 joueurs non neutres est l'initiateur.
. En commençant par l'initiateur, les joueurs vont tour à tour placer : 2 armées sur leurs territoires et 1 armée sur un territoire neutre ; jusqu'à ce que toutes les armées soient placées.
. Les cartes territoire et joker l'arbitre mélange en une pile cachée.
. L'initiateur joue le 1er tour de jeu.
