== Use Case Template

=== Revision History +

[cols=",,",options="header",]
|===
|Date |Author |Description of change
|30/12/2019 | Kowalski, Lebouis, | Report en asciidoc des cas d'utilisation fait sur papier
|===

*Use Case:* Connection joueur

*Id*: UC-1

*Description*

Un joueur se connecte au site, il entre son pseudo et indique qu'il est près à jouer.

*Level:* High Level Summary

*Primary Actor*

Joueur courant

*Supporting Actors*

Serveur

*Stakeholders and Interests*

Autres joueurs

*Pre-Conditions*

Il y a moins de 6 joueurs déjà connecté au site +
Pour jouer il faut avoir entré un pseudo

*Post Conditions*

[.underline]#Success end condition#

Le serveur a reçu le message de

[.underline]#Failure end condition#:

Il y a déjà trop de joueurs connectés +
La partie a déjà commencé

[.underline]#Minimal Guarantee#

Seul un joueur ayant validé peu accéder au jeu

*Trigger*

Connection du joueur

=== Main Success Scenario

[arabic]
. Connection du joueur
. Le joueur entre un pseudo
. Le joueur indique qu'il est près à joueur

=== Extensions

3a. Dans l'étape 3, s'il y a déjà 6 joueurs de connectés ou si la partie est déjà en cour

{empty}1. On refuse sa demande

=== Variations

2’. Etape 2, le pseudo de l'utilisateur peut varier

*Frequency:* 2 à 6 par partie

*Assumptions*

---

*Use Case:* Initialisation plateau

*Id*: UC-2

*Description*

Lorsque tous les joueurs sont près, on initialise le plateau

*Level:* High Level Summary

*Primary Actor*

Serveur

*Supporting Actors*

*Stakeholders and Interests*

Joueurs

*Pre-Conditions*

Entre 2 et 6 joueur ont entré un pseudo et validé

*Post Conditions*

[.underline]#Success end condition#

Le plateau est initialisé, les joueurs ont reçu le plateau ainsi que leurs pays et leur mission

[.underline]#Failure end condition#:

[.underline]#Minimal Guarantee#

*Trigger*

Validation de tous les joueurs connectés

=== Main Success Scenario

[arabic]
. Création du plateau
. Création des missions
. Attribution d'une mission à chaque joueur
. Création des cartes territoire
. Attributions des pays de départ à chaque joueur
. Ajout des cartes joker à la pioche
. Attribution des régiments de départ à chaque joueur

=== Extensions

=== Variations

3’. l'attribution des mission se fait de manière aléatoire
5’. l'attribution des territoire se fait de manière aléatoire

*Frequency:* 1 par partie

*Assumptions*

---

*Use Case:* Placement Initial

*Id*: UC-3

*Description*

Chaque joueur pose ses regiments sur ses pays avant le début de la partie

*Level:* High Level Summary

*Primary Actor*

Joueurs

*Supporting Actors*

Serveur

*Stakeholders and Interests*

*Pre-Conditions*

Le joueur a reçu la demande de placer ses régiments ainsi que les régiments à placer

*Post Conditions*

[.underline]#Success end condition#

Tous les joueurs ont placé tous leurs régiments

[.underline]#Failure end condition#:

Un joueur a voulu placer plus de régiments qu'il ne le pouvait, ou bien sur un territoire qu'il ne possédait pas.

[.underline]#Minimal Guarantee#

*Trigger*

Envoie d'une demande de placement initial

=== Main Success Scenario

[arabic]
. Choisir un pays
. Choisir un nombre d'unités à placer
. Envoyer le placement

=== Extensions

1a. A l'étape 1, si le pays n'appartient pas au joueur

{empty}1. On reste à l'étape 1

2a. A l'étape 2, si le joueur n'a pas assez de regiments

{empty}1. On reste à l'étape 2

3a. Après l'étape 3, s'il ne reste plus de régiments au joueur

{empty}1. On indique au serveur que l'on a terminé

3b. Sinon

{empty}1. retour à l'étape 1

=== Variations

1’. Le pays choisit peu changer
5’. Le nombre d'unités à placer peu changer

*Frequency:* 1 par partie

*Assumptions*

---

*Use Case:* Combo

*Id*: UC-4

*Description*

Le joueur entrain de jouer fait un combo

*Level:* Summary

*Primary Actor*

Joueur courant

*Supporting Actors*

Serveur

*Stakeholders and Interests*

*Pre-Conditions*

Le joueur a reçu la demande de faire un combo, et s'il le peu il envoie des cartes au serveur, trois par trois, pour fair des combos

*Post Conditions*

[.underline]#Success end condition#

Le joueur recevra des unités en plus correspondant au combo qu'il a fait

[.underline]#Failure end condition#:

Les cartes proposé ne permet aucun combo possible
Si le joueur a 5 cartes ou plus il est obligé de faire un combo jusqu'à redescendre en dessous de ce nombre

[.underline]#Minimal Guarantee#

*Trigger*

Envoie d'une demande de combo

=== Main Success Scenario

[arabic]
. Choisir la première carte
. Choisir la deuxième carte
. Choisir la troisième carte
. Envoyer les cartes au serveur

=== Extensions

1a. Si le joueur ne veut pas effectuer de combo et n'y est pas forcé

{empty}1. On indique au serveur que l'on a fini de faire des combos

3a. Après l'étape 3, s'il ne reste plus assez de cartes pour faire un combo

{empty}1. On indique au serveur que l'on a terminé

3b. Sinon

{empty}1. retour à l'étape 1

=== Variations

1’. La carte peu changer
2’. La carte peu changer
3’. La carte peu changer

*Frequency:* 1 par tour de jeu

*Assumptions*

---

*Use Case:* Placement regiment

*Id*: UC-5

*Description*

Le joueur entrain de jouer place les régiments de début de tour

*Level:* Summary

*Primary Actor*

Joueur courant

*Supporting Actors*

Serveur

*Stakeholders and Interests*

*Pre-Conditions*

Le joueur a reçu la demande de faire des placements, et tant qu'il lui reste des régiments, il fait des placements de ces régiments sur les pays et les envoi au serveur

*Post Conditions*

[.underline]#Success end condition#

Le joueur n'a plus de régiments à placer

[.underline]#Failure end condition#:

Le pays sélectionné n'est pas au joueur
Le joueur ne peux pas placer autant d'unités

[.underline]#Minimal Guarantee#

*Trigger*

Envoie d'une demande de placement

=== Main Success Scenario

[arabic]
. Selection du pays de destination
. Précision du nombre d'unités à placer
. Envoie du placement

=== Extensions

1a. Si le pays choisit n'appartient pas au joueur

{empty}1. rester à l'étape 1

3a. Après l'étape 3, s'il ne reste plus d'unités

{empty}1. On indique au serveur que l'on a terminé

3b. Sinon

{empty}1. retour à l'étape 1

=== Variations

1’. Le pays peu changer
2’. Le nombre d'unités à placer peu changer

*Frequency:* 1 par tour de jeu

*Assumptions*

---

*Use Case:* Attaque

*Id*: UC-6

*Description*

Le joueur entrain de jouer effectue des attaques

*Level:* Summary

*Primary Actor*

Joueur courant
Joueur défenseur

*Supporting Actors*

Serveur

*Stakeholders and Interests*

*Pre-Conditions*

Le joueur a reçu la demande de faire des attaques, et tant qu'il en a la possibilité, il peu faire des attaques, +
soit sélectionné un pays attaquant, un pays attaqué, et le nombre d'unités allant effectuer l'attaque. +
Le joueur défenseur indique le nombre de défenseurs sur son pays.
Le serveur effectue l'attaque en lançant les dés et en modifiant les pays en fonction du résultat de l'attaque.

*Post Conditions*

[.underline]#Success end condition#

Toutes les attaques souhaité du joueur sont faites

[.underline]#Failure end condition#:

Le pays attaquant n'appartient pas au joueur
Le pays attaqué appartient au joueur ou n'est pas un voisin du pays attaquant
Le nombre d'unité attaquant est supérieur ou égale au nombre de troupes sur le pays attaquant

[.underline]#Minimal Guarantee#

*Trigger*

Envoie d'une demande d'attaque

=== Main Success Scenario

[arabic]
. Sélectionner le pays attaquant
. Sélectionner le pays attaquer
. Indiquer le nombre d'attaquant
. Envoyer l'attaque
. Le défenseur indique le nombre de défenseur
. Le serveur effectue l'attaque

=== Extensions

1a. A l'étape 1, si le joueur ne veux pas effectuer d'attaque

{empty}1. On indique au serveur que l'on a terminé

1b. A l'étape 1, si le pays choisit n'appartient pas au joueur

{empty}1. rester à l'étape 1

2a. A l'étape 2, si le pays choisit appartient au joueur ou n'est pas voisin du pays attaquant

{empty}1. rester à l'étape 2

3a. A l'étape 3, si le nombre d'unités attaquant est supérieur ou égale au nombre d'unités du pays

{empty}1. rester à l'étape 5

5a. A l'étape 5, si le nombre d'unités defense est supérieur au nombre d'unités du pays

{empty}1. rester à l'étape 5

5b. Après l'étape 5, si le pays a été conquis

{empty}1. Le joueur indique le nombre d'unités qu'il vaut déplacer dans le pays conquis
{empty}2. Le joueur recevra une unique carte une fois l'attaque terminé

5c. Sinon

{empty}1. retour à l'étape 1.

6a. Après l'étape 5b, si le joueur vaincu a été éliminé de la partie

{empty}1. On met à jour toutes les missions des joueurs et on vérifie s'il y a un gagnant, dans ce cas, la partie s'arrête.

6b. Sinon

{empty}1. retour à l'étape 1.

=== Variations

1’. Le pays peu changer
2’. Le pays peu changer
3’. Le nombre d'unités attaquant peu changer
5’. Le nombre d'unités défenseur peu changer
5b’. Le nombre d'unités de conquête peu changer

*Frequency:* 1 par tour de jeu

*Assumptions*

---

*Use Case:* Replacement

*Id*: UC-7

*Description*

Le joueur entrain de jouer effectue des replacement

*Level:* Summary

*Primary Actor*

Joueur courant

*Supporting Actors*

Serveur

*Stakeholders and Interests*

*Pre-Conditions*

Le joueur a reçu la demande de faire des replacements, il choisit donc un pays de départ et un pays d'arrivée, voisin du premier, ainsi que le nombre d'unité devant passer de l'un à l'autre. +
une même unité ne peu se déplacer que d'un pays maximum

*Post Conditions*

[.underline]#Success end condition#

Tous les replacements souhaité du joueur sont faits

[.underline]#Failure end condition#:

Le pays de départ ou de destination n'appartiennent pas au joueurs
Les deux pays ne sont pas voisins
Le nombre d'unité à déplacer est supérieur à celui du pays de départ qui n'ont pas encore bougées

[.underline]#Minimal Guarantee#

*Trigger*

Envoie d'une demande de replacement

=== Main Success Scenario

[arabic]
. Sélectionner le pays de départ
. Sélectionner le pays d'arrivé
. Indiquer le nombre d'unités à déplacer

=== Extensions

1a. A l'étape 1, si le joueur ne veux pas effectuer d'attaque

{empty}1. On indique au serveur que l'on a terminé

1b. A l'étape 1, si le pays n'appartient pas au joueur

{empty}1. On reste à l'étape 1

2a. A l'étape 1, si le pays n'appartient pas au joueur ou n'est pas voisin du premier

{empty}1. On reste à l'étape 2

3a. A l'étape 1, si ne nombre d'unité à déplacer n'est pas correcte

{empty}1. On reste à l'étape 3

=== Variations

1’. Le pays peu changer
2’. Le pays peu changer
3’. Le nombre d'unités à déplacer peu changer

*Frequency:* 1 par tour de jeu

*Assumptions*
